### ISSUE TITLE
Add check for/remove casting player for console commands

### ISSUE THREAD

**Issue by RoboMWM** [Dankrushen/SetMyHealth#2]
I'll submit a PR for this if you don't know what I'm talking about - but this is in the Bukkit tutorial...

**Comment by Dankrushen** [comment]
I know what you mean I just have been to lazlazy to do it yet. I've been working on other things, I'm actually planning on redoing the plugin almost entirely but as just a few methods, making there be more than 100 less lines of code

**Comment by Dankrushen** [comment]
Also sorry for spelling mistakes my hands are frozen :|

**Comment by Dankrushen** [comment]
I have fixed the console not being able to send commands, will work on other plugin, but for the meantime I will just make a separate plugin just for that.
